apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mynode
  template:
    metadata:
      labels:
        app: mynode
    spec:
      containers: 
      - name: mynode
        image: node:v6
        ports:
        - containerPort:3001 
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: mynode
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 32502